name: CrewBus
options:
  bundleIdPrefix: com.crewbus
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

packages:
  CrewBusKit:
    path: ../CrewBusKit

targets:
  CrewBus:
    type: application
    platform: macOS
    sources:
      - CrewBus/Sources
    resources:
      - CrewBus/Resources
    dependencies:
      - package: CrewBusKit
    info:
      path: CrewBus/Resources/Info.plist
      properties:
        CFBundleDisplayName: Crew Bus
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSApplicationCategoryType: public.app-category.utilities
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.crewbus.mac
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.9"
      DEVELOPMENT_TEAM: ""
    entitlements:
      path: CrewBus/Resources/CrewBus.entitlements
