name: CrewBus
options:
  bundleIdPrefix: com.crewbus
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

targets:
  CrewBus:
    type: application
    platform: iOS
    sources:
      - CrewBus/Sources
    resources:
      - CrewBus/Resources
    info:
      path: CrewBus/Resources/Info.plist
      properties:
        CFBundleDisplayName: Crew Bus
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.crewbus.app
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.9"
      DEVELOPMENT_TEAM: ""
