name = "crewbus-relay"
main = "worker.ts"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
    { name = "TUNNEL", class_name = "TunnelDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TunnelDurableObject"]

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "426929d9842a47c68c7ba685bc43e07a"

[[kv_namespaces]]
binding = "TUNNEL_KV"
id = "e73ac3e013ed4705b138526536c5424a"

[vars]
RELAY_ORIGIN = "https://relay.crew-bus.dev"
